services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment: 
      SA_PASSWORD: "9SO@T123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./ScriptCriacaoTabelas.sql:/tmp/ScriptCriacaoTabelas.sql
    command: /bin/bash -c "sleep 15 && /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 9SO@T123 -d master -i /tmp/ScriptCriacaoTabelas.sql"
  fiap.API:
    image: ${DOCKER_REGISTRY-}fiap-api
    build:
      context: .
      dockerfile: /Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - "5272:5272"
    depends_on: 
    - mssqltools 
