apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fiap-fase-2-hpa
  labels: 
     app: fiap-fase-2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fiap-fase-2
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40