apiVersion: apps/v1 
kind: Deployment
metadata:
  name: fiap-fase-2
  labels: 
     app: fiap-fase-2

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: fiap-fase-2

  template:
    metadata:
      labels:
        app: fiap-fase-2
    spec:
      containers:
      - name: fiap-fase-2
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - name: http
          port: 80
          targetPort: 80
        - name: https
          port: 443
          targetPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1