apiVersion: v1
kind: Service
metadata:
  name: kubernetes-fiap-fase-2-service
  labels:
    app: fiap-fase-2 
spec:
  selector:
    app: fiap-fase-2 

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer