apiVersion: apps/v1 
kind: Deployment
metadata:
  name: fiap-fase-2
  labels: 
     app: fiap-fase-2
spec:
  selector:
    matchLabels:
      app: fiap-fase-2
      version: v01
  template:
    metadata:
      labels:
        app: fiap-fase-2
        version: v01
    spec:
      serviceAccountName: fiap-fase-2-account
      imagePullSecrets: 
        - name: docker-auth
      restartPolicy: Always
      containers:
      - name: fiap-fase-2
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
        env: 
        - name: "ASPNETCORE_ENVIROMENT"
          value: "Development"
---
apiVersion: v1
kind: Pod
metadata:
  name: fiap-fase-2
spec:
  containers:
  - name: fiap-fase-2
    image: DOCKER_IMAGE
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"